adra/urls.py
from django.urls import path, include
from rest_framework.authtoken import views as vs
from rest_framework.routers import DefaultRouter

from . import views
from .views import (
    PersonaDetailView,
    PersonaCreateView,
    PersonaUpdateView, PersonaDeleteView,
    PersonaAlimentosDeleteView,
    AlmacenListView,
    HijoUpdateView,
    HijoDeleteView,
    PersonaListView,
    PersonaAlimentosUpdateView

)

app_name = 'adra'
# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'personas', views.PersonaViewSet)
router.register(r'almacen', views.AlmacenViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('api/', include((router.urls, 'api'), namespace='api')),
    path('api-token-auth/', vs.obtain_auth_token, name="api-token-auth"),

    # personas url
    path('', PersonaListView.as_view(), name="persona-home"),
    path('persona/<int:pk>/', PersonaDetailView.as_view(), name="personas_detail"),
    path('persona/new/', PersonaCreateView.as_view(), name="persona-create"),
    path('persona/<int:pk>/update/', PersonaUpdateView.as_view(),
         name="persona-update"),
    path('persona/<int:pk>/delete/', PersonaDeleteView.as_view(),
         name="persona-delete"),
    # end persona url

    # almacen url
    path('almacen/', AlmacenListView.as_view(), name="almacen-home"),
    # end almacen url

    # statistics
    path('statistics/', views.statistics_persona, name="statistics-personas"),
    path('telegram/', views.telegram_messages, name="telegram_message_view"),
    path('export/csv/', views.export_users_csv, name='exportar-users-csv'),
    path('export/pdf/<int:pk>', views.generar_hoja_entrega, name='pdf_form'),
    path('export/docx/<int:pk>', views.generar_hoja_valoracion_social, name='docx_form'),
    # end statistics

    # buscar url
    path('buscar/', views.buscar, name="buscar"),
    path('buscar_por_fecha/', views.buscar_fecha, name='buscar-por-fecha'),
    # end bucar url

    # alimentos url
    path('persona/<int:pk>/alimentos', views.adauga_alimentos_persona,
         name="alimentos-create"),
    path('persona/alimentos/<int:pk>/update',
         PersonaAlimentosUpdateView.as_view(), name='persona-update-alimentos'),

    path('persona/alimentos/<int:pk>/delete',
         PersonaAlimentosDeleteView.as_view(), name='persona-alimentos-delete'),
    # end alimentos url

    # hijos url
    path('persona/<int:pk>/hijos', views.adauga_hijo_persona,
         name="hijo-create"),
    path('persona/hijos/<int:pk>/update', HijoUpdateView.as_view(),
         name="hijo-update"),
    path('persona/hijos/<int:pk>/delete', HijoDeleteView.as_view(),
         name="hijo-delete"),
    # end hijos url
    path('edit/', views.edit, name='edit-profile'),
    path('get-data/', views.get_data, name='get_data'),
    path('get-beneficiarios-activos/<int:number>', views.get_beneficiarios_activos, name='get_beneficiarios_activos'),
    path('adra-anuncios/', views.anuncios, name='anuncio'),
    path('reset-papeles/', views.reset_papeles, name='reset-papeles'),

]

adra_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django admin
    path('toate-dar-admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # User management
    path('accounts/', include('allauth.urls')),
    # local apps
    # path('accounts/', include('users.urls')),
    path('', include('adra.urls', namespace="adra")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adra/forms.py
from django import forms
from .models import Persona, Alimentos, Hijo, Profile
from django.contrib.auth.models import User
from django.forms import ModelForm, DateInput, EmailInput, Form


class AlimentosFrom(ModelForm):
    class Meta:
        model = Alimentos
        fields = (
            'alimento_1',
            'alimento_2',
            'alimento_3',
            'alimento_4',
            'alimento_5',
            'alimento_6',
            'alimento_7',
            'alimento_8',
            'alimento_9',
            'alimento_10',
            'alimento_11',
            'alimento_12',
            'fecha_recogida'
        )
        widgets = {
            'fecha_recogida': DateInput(attrs={"type": "date"}),
        }


class PersonaForm(ModelForm):
    class Meta:
        model = Persona
        fields = [
            'nombre_apellido',
            'dni',
            'fecha_nacimiento',
            'numero_adra',
            'nacionalidad',
            'domicilio',
            'are_acte',
            'ciudad',
            'telefono',
            'mensaje',
            'sexo',
            'discapacidad',
            'domingo',
            'empadronamiento',
            'libro_familia',
            'fotocopia_dni',
            'prestaciones',
            'nomnia',
            'cert_negativo',
            'aquiler_hipoteca',
            'recibos',
            'email',
            'covid',

        ]
        widgets = {
            'fecha_nacimiento': DateInput(attrs={"type": "date"}),
            'email': EmailInput(attrs={"type": "email"})
        }


class HijoForm(ModelForm):
    class Meta:
        model = Hijo
        fields = [
            'parentesco',
            'nombre_apellido',
            'dni',
            'fecha_nacimiento',

        ]
        widgets = {
            'fecha_nacimiento': DateInput(attrs={"type": "date"}),
        }


class UserEditForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth',)
        widgets = {
            'date_of_birth': DateInput(attrs={"type": "text"}),
        }


class SignupForm(Form):
    first_name = forms.CharField(max_length=30, label='Nume')
    last_name = forms.CharField(max_length=30, label='Prenume')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

adra/views.py
import logging
import os
import time
from datetime import date
import telegram
from PyPDF2 import PdfFileReader, PdfFileWriter
from PyPDF2.generic import BooleanObject, NameObject, IndirectObject
from allauth.account.adapter import DefaultAccountAdapter
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import connection
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import (ListView, DetailView, DeleteView, UpdateView, CreateView)
from mailmerge import MailMerge
from openpyxl import Workbook
from openpyxl.styles import Alignment, PatternFill
from rest_framework import permissions
from rest_framework import viewsets
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (Mail)

from .filters import AlimentosFilters
from .forms import AlimentosFrom, HijoForm, PersonaForm, ProfileEditForm, UserEditForm
from .models import Persona, Alimentos, AlmacenAlimentos, Hijo
from .serializers import PersonaSerializer, AlacenAlimentosSerializer, UserSerializer

logger = logging.getLogger(__name__)


def anuncios(request):
    return render(request, 'adra/anuncio.html')


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request, 'El perfil se ha actualizado correctamente')
            return redirect('adra:edit-profile')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit-perfile.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


class PersonaListView(LoginRequiredMixin, ListView):
    template_name = 'adra/index.html'
    context_object_name = 'ultima_persona'
    model = Persona
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # enviar al misma pagina varios contextos
        context['hijo'] = Hijo.objects
        context['hijomenor'] = Hijo
        context['nbar'] = "home"
        context['debug'] = settings.DEBUG
        context['platform_name'] = settings.PLATFORM_NAME

        return context


# ir a la pagina detallada de cada persona
class PersonaDetailView(LoginRequiredMixin, DetailView):
    model = Persona
    template_name = 'adra/detail.html'
    context_object_name = 'persona'
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AlimentosFilters(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class BuscarDetailView(LoginRequiredMixin, ListView):
    model = Alimentos
    template_name = 'busqueda_a/view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AlimentosFilters(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class PersonaCreateView(LoginRequiredMixin, CreateView):
    model = Persona
    success_url = '/'
    form_class = PersonaForm

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        messages.add_message(self.request, messages.SUCCESS, 'Beneficiaru sa adaugat cu success!')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            p = Persona.objects.latest('created_at')
            context['nbar'] = "create"
            context['bas'] = p
            return context
        except Persona.DoesNotExist:
            pass


class PersonaUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Persona
    fields = [
        'nombre_apellido',
        'dni',
        'fecha_nacimiento',
        'numero_adra',
        'nacionalidad',
        'domicilio',
        'are_acte',
        'ciudad',
        'telefono',
        'mensaje',
        'sexo',
        'discapacidad',
        'domingo',
        'empadronamiento',
        'libro_familia',
        'fotocopia_dni',
        'prestaciones',
        'nomnia',
        'cert_negativo',
        'aquiler_hipoteca',
        'recibos',
        'email',
        'covid'
    ]
    success_message = 'Datele sau salvat cu success!!'

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['up'] = "update"
        return context


class PersonaDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Persona
    success_message = 'Beneficirio borrado corectamente'
    success_url = '/'


def adauga_alimentos_persona(request, pk):
    persona = get_object_or_404(Persona, pk=pk)
    almacen = AlmacenAlimentos.objects.get(pk=1)

    if request.method == 'POST':
        a_form = AlimentosFrom(request.POST)
        if a_form.is_valid():
            alimentos = a_form.save(commit=False)

            almacen.alimento_1 -= alimentos.alimento_1
            almacen.alimento_2 -= alimentos.alimento_2
            almacen.alimento_3 -= alimentos.alimento_3
            almacen.alimento_4 -= alimentos.alimento_4
            almacen.alimento_5 -= alimentos.alimento_5
            almacen.alimento_6 -= alimentos.alimento_6
            almacen.alimento_7 -= alimentos.alimento_7
            almacen.alimento_8 -= alimentos.alimento_8
            almacen.alimento_9 -= alimentos.alimento_9
            almacen.alimento_10 -= alimentos.alimento_10
            almacen.alimento_11 -= alimentos.alimento_11
            almacen.alimento_12 -= alimentos.alimento_12

            alimentos.persona = persona
            alimentos.modificado_por = request.user
            almacen.save()
            alimentos.save()
            logger.warning("aliemnte sau dat beneficiarului")
            messages.success(request, 'Los alimentos se han entregado correctamente!')
            return redirect(persona)

    else:
        a_form = AlimentosFrom()
    return render(request, 'adra/alimentos_form.html', {'form': a_form})


class PersonaAlimentosUpdateView(LoginRequiredMixin, UpdateView):
    model = Alimentos
    fields = [
        'alimento_1',
        'alimento_2',
        'alimento_3',
        'alimento_4',
        'alimento_5',
        'alimento_6',
        'alimento_7',
        'alimento_8',
        'alimento_9',
        'alimento_10',
        'alimento_11',
        'alimento_12',
        'fecha_recogida'

    ]

    def form_valid(self, form):
        clean = form.changed_data
        almacen = AlmacenAlimentos.objects.get(pk=1)

        if "alimento_1" in clean:
            valor_anterior_alimento_1 = form.initial["alimento_1"]
            if form.instance.alimento_1 > valor_anterior_alimento_1:
                restante = abs(form.instance.alimento_1 - valor_anterior_alimento_1)
                almacen.alimento_1 -= restante
            else:
                restante = abs(form.instance.alimento_1 - valor_anterior_alimento_1)
                almacen.alimento_1 += restante

        if "alimento_2" in clean:
            valor_anterior_alimento_2 = form.initial["alimento_2"]
            if form.instance.alimento_2 > valor_anterior_alimento_2:
                restante = abs(form.instance.alimento_2 - valor_anterior_alimento_2)
                almacen.alimento_2 -= restante
            else:
                restante = abs(form.instance.alimento_2 - valor_anterior_alimento_2)
                almacen.alimento_2 += restante

        if "alimento_3" in clean:
            valor_anterior_alimento_3 = form.initial["alimento_3"]
            if form.instance.alimento_3 > valor_anterior_alimento_3:
                restante = abs(form.instance.alimento_3 - valor_anterior_alimento_3)
                almacen.alimento_3 -= restante
            else:
                restante = abs(form.instance.alimento_3 - valor_anterior_alimento_3)
                almacen.alimento_3 += restante

        if "alimento_4" in clean:
            valor_anterior_alimento_4 = form.initial["alimento_4"]
            if form.instance.alimento_4 > valor_anterior_alimento_4:
                restante = abs(form.instance.alimento_4 - valor_anterior_alimento_4)
                almacen.alimento_4 -= restante
            else:
                restante = abs(form.instance.alimento_4 - valor_anterior_alimento_4)
                almacen.alimento_4 += restante

        if "alimento_5" in clean:
            valor_anterior_alimento_5 = form.initial["alimento_5"]
            if form.instance.alimento_5 > valor_anterior_alimento_5:
                restante = abs(form.instance.alimento_5 - valor_anterior_alimento_5)
                almacen.alimento_5 -= restante
            else:
                restante = abs(form.instance.alimento_5 - valor_anterior_alimento_5)
                almacen.alimento_5 += restante

adra/templates/adra/alimentos_confirm_delete.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
    {% block content %}
        <div class="col-md-8">
            <h1>Personas</h1>
            <form method="POST">
                {% csrf_token %}
                <h1>Chiar vrei sa stergi la entrega con fecha de "{{ object.created_at|date:"Y-m-d" }}" ?</h1>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Sterge</button>
                    <a href=" {% url 'adra:persona-home' %}" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    {% endblock %}
</div>

adra/templates/adra/alimentos_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
    {% block content %}
    <div class="col-md-12 p-3" style="box-shadow: 0px 0px 23px -2px rgba(186,186,186,1);">
        <h2 class="display-5 pb-4">Adauga alimente persoanei</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_1|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_2|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_3|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_4|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_5|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_6|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_7|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_8|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_9|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_10|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_11|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.alimento_12|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12 mb-0">
                    {{ form.fecha_recogida|as_crispy_field }}
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-info btn-block btn-lg" type="submit">Adauga</button>
            </div>
        </form>
    </div>
    {% endblock %}

</div>

adra/templates/adra/anuncio.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">
        <h1 style="color: red;margin-top: 5%;">Adra Torrejon Informa</h1>
        <p style="font-size: 18px;"><b>A partir de ahora ya no vamos a enviar mensajes</b>  </p>
        <p><b>La via de comunicación sera a traves de <span class="text-danger" style="font-size: 24px;"> telegram</span> que os paso el enlace para descargar</b></p>
        <p><b> <a href="https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=es">Android</a></b></p>
        <p><b> <a href="https://apps.apple.com/es/app/telegram-messenger/id686449807">Iphone</a></b></p>
        <p><b>Una vez instalada ,teneis que pulsar este enlace de abajo y uniros al chat que he creado para hablar con vosotros,es urgente</b></p>
        <p><b><a href="https://t.me/joinchat/AAAAAFXCpY63-5afLQbkcA">Chat Adra</a></b></p>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

adra/templates/adra/detail.html
<!-- {% extends "_base.html" %} -->
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    {{ persona.nombre_apellido }}
{% endblock %}



{% block content %}


    <div class="profile-container" style="box-shadow: 0px 0px 23px -2px rgba(186,186,186,1);">
        <div class="row">
            <div class="col-md-4 col-xs-12 mb-5 d-flex pt-3 justify-content-center">
                {% if object.sexo == "hombre" %}
                    <img src="{% static 'images/chico.png' %}" class="img-responsive" width="100" height="100"/>
                {% else %}
                    <img src="{% static 'images/girl.png' %}" class="img-responsive" width="100" height="100"/>
                {% endif %}
            </div>
            <div class="col-md-8 col-xs-12  profile-info mb-5 p-xs-1 pt-md-3 text-lg-left text-center">
                <h2 class="user-name" title="nombre del beneficiario"> {{ object.nombre_apellido }}</h2>
                <h3 class="user-mail" title="fecha de nacimiento">{{ object.fecha_nacimiento }} </h3>
                <h5 class="user-company " title="numero adra" style="font-size: 32px;"> {{ object.numero_adra }}</h5>
            </div>
        </div>
        <div class="row " style="border-bottom: 2px solid darkslategrey;margin-bottom: 20px;">
            <ul class="list-group list-group-flush ">
                <li class="list-group-item ">

                    <a class="btn " data-toggle="tooltip" data-placement="top"
                       title="Editar la informacion del beneficiario" role="button"
                       href="{% url 'adra:persona-update' persona.id %}">
                        <i class="large material-icons" title=""
                           style="font-size: 36px;color: darkslategrey">portrait</i>
                    </a>
                    <a class="btn" data-toggle="modal" data-target="#modalListadoAlimentos" role="button"
                       style="color: white">
                        <i class="large material-icons" title="ver alimentos entregados"
                           style="font-size: 36px;color: darkslategrey">assignment</i>
                    </a>
                    <a class="btn " data-toggle="modal" data-target="#modalListadoFamiliares" role="button"
                       style="color: white">
                        <i class="large material-icons" title="ver familiares beneficiario"
                           style="font-size: 36px;color: darkslategrey">people</i>
                    </a>
                    <a class="btn" data-toggle="tooltip" data-placement="top" title="Añadir alimentos beneficiario"
                       role="button" href="{% url 'adra:alimentos-create' persona.id %}">
                        <i class="large material-icons"
                           style="font-size: 36px;color: darkslategrey">local_dining</i>
                    </a>
                    <a class="btn" data-toggle="tooltip" data-placement="top" title="Añadir familiares" role="button"
                       href="{% url 'adra:hijo-create' persona.id %}">
                        <i class="large material-icons"
                           style="font-size: 36px;color: darkslategrey">group_add</i>
                    </a>
                    <a class="btn" data-toggle="tooltip" data-placement="top" title="Generar hoja de entrega"
                       role="button"
                       href="{% url 'adra:pdf_form' persona.id %}">
                        <i class="large material-icons"
                           style="font-size: 36px;color: darkslategrey">picture_as_pdf</i>
                    </a>
                    <a class="btn" data-toggle="tooltip" data-placement="top" title="Generar hoja de valoracion social"
                       role="button"
                       href="{% url 'adra:docx_form' persona.id %}">
                        <i class="large material-icons"
                           style="font-size: 36px;color: darkslategrey">file_download</i>
                    </a>

                </li>
            </ul>
        </div>


        <div class="row more-info p-2">
            <div class="col-md-4">
                <h5><b>Documento de identidad</b></h5>
                <p> {{ object.dni }}</p>
            </div>
            <div class="col-md-4">
                <h5><b>Sexo</b></h5>
                <p>{{ object.sexo|capfirst }}</p>
            </div>
            <div class="col-md-4">
                <h5><b>Domingo</b></h5>
                <p>{{ object.domingo }}</p> <!-- </3 :( -->
            </div>
        </div>
        <div class="row more-info p-2">
            <div class="col-md-4">
                <h5><b>Nacionalidad</b></h5>
                <p>{{ object.nacionalidad }}</p>
            </div>
            <div class="col-md-4">
                <h5><b>Papeles</b></h5>
                <p>{% if object.are_acte %}
                    da{% else %} nu{% endif %}</p>
            </div>
            <div class="col-md-4">
                <h5><b>Documentacíon traida</b></h5>
                <p><a href="#" data-toggle="modal" data-target="#exampleModal">Ver
                    paples traidos</a></p>
            </div>
        </div>
        <div class="row more-info p-2">
            <div class="col-md-4">
                <h5><b>Numero de entregas</b></h5>
                <p> {{ persona.alimentos.count }}</p>
            </div>
            <div class="col-md-4">
                <h5><b>Telefono</b></h5>
                <p><a href="tel:{{ object.telefono }}"> {{ object.telefono }}</a></p>
            </div>
            <div class="col-md-4">
                <h5><b>Modificado por</b></h5>
                <p>{{ object.modificado_por|capfirst }}</p>
            </div>
        </div>
        <div class="row more-info p-2">
            <div class="col-md-6">
                <h5><b>Ciudad</b></h5>
                <p> {{ object.ciudad }}</p>
            </div>
            <div class="col-md-6">
                <h5><b>Domicilio</b></h5>
                <p>{{ object.domicilio }}</p>
            </div>
        </div>

        <div class="row p-2">
            <div class="col-md-8 bg-warning p-2">
                <h5><b>Mensaje</b></h5>
                <p style="word-wrap: break-word;"> {{ persona.mensaje }}</p>
            </div>
            <div class="col-md-4  more-info p-2">
                <h5><b>Edad</b></h5>
                <p> {{ persona.age }}</p>
            </div>

        </div>
    </div>

{% endblock %}

adra/templates/adra/hijo_confirm_delete.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
    {% block content %}
        <div class="col-md-8">
            <h1>FAMILIAR</h1>
            <form method="POST">
                {% csrf_token %}
                <h1>Quieres borrar el familiar "{{ object.nombre_apellido }}" ?</h1>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Borrrar</button>
                    <a href=" {% url 'adra:persona-home' %}" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    {% endblock %}
</div>

adra/templates/adra/hijo_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
    {% block content %}

    <div class="col-md-12 p-3" style="box-shadow: 0px 0px 23px -2px rgba(186,186,186,1);">
        <h1>Adauga Familiar</h1>
        <form method="POST">
            {% csrf_token %}

            {{ form|crispy }}

            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Adauga</button>
            </div>
        </form>
    </div>

    {% endblock %}
</div>