adra/urls.py
from django.urls import path, include
from rest_framework.authtoken import views as vs
from rest_framework.routers import DefaultRouter

from . import views
from .views import (
    PersonaDetailView,
    PersonaCreateView,
    PersonaUpdateView, PersonaDeleteView,
    PersonaAlimentosDeleteView,
    AlmacenListView,
    HijoUpdateView,
    HijoDeleteView,
    PersonaListView,
    PersonaAlimentosUpdateView

)

app_name = 'adra'
# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'personas', views.PersonaViewSet)
router.register(r'almacen', views.AlmacenViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('api/', include((router.urls, 'api'), namespace='api')),
    path('api-token-auth/', vs.obtain_auth_token, name="api-token-auth"),

    # personas url
    path('', PersonaListView.as_view(), name="persona-home"),
    path('persona/<int:pk>/', PersonaDetailView.as_view(), name="personas_detail"),
    path('persona/new/', PersonaCreateView.as_view(), name="persona-create"),
    path('persona/<int:pk>/update/', PersonaUpdateView.as_view(),
         name="persona-update"),
    path('persona/<int:pk>/delete/', PersonaDeleteView.as_view(),
         name="persona-delete"),
    # end persona url

    # almacen url
    path('almacen/', AlmacenListView.as_view(), name="almacen-home"),
    # end almacen url

    # statistics
    path('statistics/', views.statistics_persona, name="statistics-personas"),
    path('telegram/', views.telegram_messages, name="telegram_message_view"),
    path('export/csv/', views.export_users_csv, name='exportar-users-csv'),
    path('export/pdf/<int:pk>', views.generar_hoja_entrega, name='pdf_form'),
    path('export/docx/<int:pk>', views.generar_hoja_valoracion_social, name='docx_form'),
    # end statistics

    # buscar url
    path('buscar/', views.buscar, name="buscar"),
    path('buscar_por_fecha/', views.buscar_fecha, name='buscar-por-fecha'),
    # end bucar url

    # alimentos url
    path('persona/<int:pk>/alimentos', views.adauga_alimentos_persona,
         name="alimentos-create"),
    path('persona/alimentos/<int:pk>/update',
         PersonaAlimentosUpdateView.as_view(), name='persona-update-alimentos'),

    path('persona/alimentos/<int:pk>/delete',
         PersonaAlimentosDeleteView.as_view(), name='persona-alimentos-delete'),
    # end alimentos url

    # hijos url
    path('persona/<int:pk>/hijos', views.adauga_hijo_persona,
         name="hijo-create"),
    path('persona/hijos/<int:pk>/update', HijoUpdateView.as_view(),
         name="hijo-update"),
    path('persona/hijos/<int:pk>/delete', HijoDeleteView.as_view(),
         name="hijo-delete"),
    # end hijos url
    path('edit/', views.edit, name='edit-profile'),
    path('get-data/', views.get_data, name='get_data'),
    path('get-beneficiarios-activos/<int:number>', views.get_beneficiarios_activos, name='get_beneficiarios_activos'),
    path('adra-anuncios/', views.anuncios, name='anuncio'),
    path('reset-papeles/', views.reset_papeles, name='reset-papeles'),

]

adra_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django admin
    path('toate-dar-admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # User management
    path('accounts/', include('allauth.urls')),
    # local apps
    # path('accounts/', include('users.urls')),
    path('', include('adra.urls', namespace="adra")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adra/forms.py
from django import forms
from .models import Persona, Alimentos, Hijo, Profile
from django.contrib.auth.models import User
from django.forms import ModelForm, DateInput, EmailInput, Form


class AlimentosFrom(ModelForm):
    class Meta:
        model = Alimentos
        fields = (
            'alimento_1',
            'alimento_2',
            'alimento_3',
            'alimento_4',
            'alimento_5',
            'alimento_6',
            'alimento_7',
            'alimento_8',
            'alimento_9',
            'alimento_10',
            'alimento_11',
            'alimento_12',
            'fecha_recogida'
        )
        widgets = {
            'fecha_recogida': DateInput(attrs={"type": "date"}),
        }


class PersonaForm(ModelForm):
    class Meta:
        model = Persona
        fields = [
            'nombre_apellido',
            'dni',
            'fecha_nacimiento',
            'numero_adra',
            'nacionalidad',
            'domicilio',
            'are_acte',
            'ciudad',
            'telefono',
            'mensaje',
            'sexo',
            'discapacidad',
            'domingo',
            'empadronamiento',
            'libro_familia',
            'fotocopia_dni',
            'prestaciones',
            'nomnia',
            'cert_negativo',
            'aquiler_hipoteca',
            'recibos',
            'email',
            'covid',

        ]
        widgets = {
            'fecha_nacimiento': DateInput(attrs={"type": "date"}),
            'email': EmailInput(attrs={"type": "email"})
        }


class HijoForm(ModelForm):
    class Meta:
        model = Hijo
        fields = [
            'parentesco',
            'nombre_apellido',
            'dni',
            'fecha_nacimiento',

        ]
        widgets = {
            'fecha_nacimiento': DateInput(attrs={"type": "date"}),
        }


class UserEditForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth',)
        widgets = {
            'date_of_birth': DateInput(attrs={"type": "text"}),
        }


class SignupForm(Form):
    first_name = forms.CharField(max_length=30, label='Nume')
    last_name = forms.CharField(max_length=30, label='Prenume')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

adra/views.py
import logging
import os
import time
from datetime import date
import telegram
from PyPDF2 import PdfFileReader, PdfFileWriter
from PyPDF2.generic import BooleanObject, NameObject, IndirectObject
from allauth.account.adapter import DefaultAccountAdapter
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import connection
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import (ListView, DetailView, DeleteView, UpdateView, CreateView)
from mailmerge import MailMerge
from openpyxl import Workbook
from openpyxl.styles import Alignment, PatternFill
from rest_framework import permissions
from rest_framework import viewsets
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (Mail)

from .filters import AlimentosFilters
from .forms import AlimentosFrom, HijoForm, PersonaForm, ProfileEditForm, UserEditForm
from .models import Persona, Alimentos, AlmacenAlimentos, Hijo
from .serializers import PersonaSerializer, AlacenAlimentosSerializer, UserSerializer

logger = logging.getLogger(__name__)


def anuncios(request):
    return render(request, 'adra/anuncio.html')


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request, 'El perfil se ha actualizado correctamente')
            return redirect('adra:edit-profile')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit-perfile.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


class PersonaListView(LoginRequiredMixin, ListView):
    template_name = 'adra/index.html'
    context_object_name = 'ultima_persona'
    model = Persona
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # enviar al misma pagina varios contextos
        context['hijo'] = Hijo.objects
        context['hijomenor'] = Hijo
        context['nbar'] = "home"
        context['debug'] = settings.DEBUG
        context['platform_name'] = settings.PLATFORM_NAME

        return context


# ir a la pagina detallada de cada persona
class PersonaDetailView(LoginRequiredMixin, DetailView):
    model = Persona
    template_name = 'adra/detail.html'
    context_object_name = 'persona'
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AlimentosFilters(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class BuscarDetailView(LoginRequiredMixin, ListView):
    model = Alimentos
    template_name = 'busqueda_a/view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AlimentosFilters(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class PersonaCreateView(LoginRequiredMixin, CreateView):
    model = Persona
    success_url = '/'
    form_class = PersonaForm

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        messages.add_message(self.request, messages.SUCCESS, 'Beneficiaru sa adaugat cu success!')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            p = Persona.objects.latest('created_at')
            context['nbar'] = "create"
            context['bas'] = p
            return context
        except Persona.DoesNotExist:
            pass


class PersonaUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Persona
    fields = [
        'nombre_apellido',
        'dni',
        'fecha_nacimiento',
        'numero_adra',
        'nacionalidad',
        'domicilio',
        'are_acte',
        'ciudad',
        'telefono',
        'mensaje',
        'sexo',
        'discapacidad',
        'domingo',
        'empadronamiento',
        'libro_familia',
        'fotocopia_dni',
        'prestaciones',
        'nomnia',
        'cert_negativo',
        'aquiler_hipoteca',
        'recibos',
        'email',
        'covid'
    ]
    success_message = 'Datele sau salvat cu success!!'

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['up'] = "update"
        return context


class PersonaDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Persona
    success_message = 'Beneficirio borrado corectamente'
    success_url = '/'


def adauga_alimentos_persona(request, pk):
    persona = get_object_or_404(Persona, pk=pk)
    almacen = AlmacenAlimentos.objects.get(pk=1)

    if request.method == 'POST':
        a_form = AlimentosFrom(request.POST)
        if a_form.is_valid():
            alimentos = a_form.save(commit=False)

            almacen.alimento_1 -= alimentos.alimento_1
            almacen.alimento_2 -= alimentos.alimento_2
            almacen.alimento_3 -= alimentos.alimento_3
            almacen.alimento_4 -= alimentos.alimento_4
            almacen.alimento_5 -= alimentos.alimento_5
            almacen.alimento_6 -= alimentos.alimento_6
            almacen.alimento_7 -= alimentos.alimento_7
            almacen.alimento_8 -= alimentos.alimento_8
            almacen.alimento_9 -= alimentos.alimento_9
            almacen.alimento_10 -= alimentos.alimento_10
            almacen.alimento_11 -= alimentos.alimento_11
            almacen.alimento_12 -= alimentos.alimento_12

            alimentos.persona = persona
            alimentos.modificado_por = request.user
            almacen.save()
            alimentos.save()
            logger.warning("aliemnte sau dat beneficiarului")
            messages.success(request, 'Los alimentos se han entregado correctamente!')
            return redirect(persona)

    else:
        a_form = AlimentosFrom()
    return render(request, 'adra/alimentos_form.html', {'form': a_form})


class PersonaAlimentosUpdateView(LoginRequiredMixin, UpdateView):
    model = Alimentos
    fields = [
        'alimento_1',
        'alimento_2',
        'alimento_3',
        'alimento_4',
        'alimento_5',
        'alimento_6',
        'alimento_7',
        'alimento_8',
        'alimento_9',
        'alimento_10',
        'alimento_11',
        'alimento_12',
        'fecha_recogida'

    ]

    def form_valid(self, form):
        clean = form.changed_data
        almacen = AlmacenAlimentos.objects.get(pk=1)

        if "alimento_1" in clean:
            valor_anterior_alimento_1 = form.initial["alimento_1"]
            if form.instance.alimento_1 > valor_anterior_alimento_1:
                restante = abs(form.instance.alimento_1 - valor_anterior_alimento_1)
                almacen.alimento_1 -= restante
            else:
                restante = abs(form.instance.alimento_1 - valor_anterior_alimento_1)
                almacen.alimento_1 += restante

        if "alimento_2" in clean:
            valor_anterior_alimento_2 = form.initial["alimento_2"]
            if form.instance.alimento_2 > valor_anterior_alimento_2:
                restante = abs(form.instance.alimento_2 - valor_anterior_alimento_2)
                almacen.alimento_2 -= restante
            else:
                restante = abs(form.instance.alimento_2 - valor_anterior_alimento_2)
                almacen.alimento_2 += restante

        if "alimento_3" in clean:
            valor_anterior_alimento_3 = form.initial["alimento_3"]
            if form.instance.alimento_3 > valor_anterior_alimento_3:
                restante = abs(form.instance.alimento_3 - valor_anterior_alimento_3)
                almacen.alimento_3 -= restante
            else:
                restante = abs(form.instance.alimento_3 - valor_anterior_alimento_3)
                almacen.alimento_3 += restante

        if "alimento_4" in clean:
            valor_anterior_alimento_4 = form.initial["alimento_4"]
            if form.instance.alimento_4 > valor_anterior_alimento_4:
                restante = abs(form.instance.alimento_4 - valor_anterior_alimento_4)
                almacen.alimento_4 -= restante
            else:
                restante = abs(form.instance.alimento_4 - valor_anterior_alimento_4)
                almacen.alimento_4 += restante

        if "alimento_5" in clean:
            valor_anterior_alimento_5 = form.initial["alimento_5"]
            if form.instance.alimento_5 > valor_anterior_alimento_5:
                restante = abs(form.instance.alimento_5 - valor_anterior_alimento_5)
                almacen.alimento_5 -= restante
            else:
                restante = abs(form.instance.alimento_5 - valor_anterior_alimento_5)
                almacen.alimento_5 += restante

adra/templates/adra_almacen/index.html
{% extends "_base.html" %}
{% load verbose_names %}

{% block title %}
    Almacen
{% endblock %}
<div class="row">
    {% block content %}


        <div class="col-md-12">
            <aside class="profile-nav alt">
                <section class="card">
                    <div class="card-header user-header alt bg-dark">
                        <div class="media">

                            <div class="media-body">
                                <h2 class="text-light display-6">Almacen</h2>
                                <p class="text-danger">Unidades disponibles</p>
                            </div>
                        </div>
                    </div>


                    <ul class="list-group list-group-flush">
                        {% for alimento in almacen_adra %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {% get_verbose_field_name alimento "alimento_1" %}
                                <span class="badge badge-primary">{{ alimento.alimento_1 }}</span>
                            </li>

                            <li class="list-group-item  d-flex justify-content-between align-items-center">
                                {% get_verbose_field_name alimento "alimento_2" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_2 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {% get_verbose_field_name alimento "alimento_3" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_3 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {% get_verbose_field_name alimento "alimento_4" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_4 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {% get_verbose_field_name alimento "alimento_5" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_5 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_6" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_6 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_7" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_7 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_8" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_8 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_9" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_9 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_10" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_10 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_11" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_11 }}</span>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                {% get_verbose_field_name alimento "alimento_12" %}
                                <span class="badge badge-primary ">{{ alimento.alimento_12 }}</span>

                            </li>
                        {% empty %}
                            <p>Almacen vacio</p>
                        {% endfor %}
                    </ul>

                </section>
            </aside>
        </div>





        <!--
    <div class="col-md-12 col-sm-12">

        <table class="table  table-sm table-responsive">
            <thead>
                <tr>
                    <th scope="col">Aroz Blanco</th>
                    <th scope="col">Garbanzo cocido</th>
                    <th scope="col">Atun</th>
                    <th scope="col">Sardina</th>
                    <th scope="col">Pasta Espagueti</th>
                    <th scope="col">Tomate Frito</th>
                    <th scope="col">Galletas</th>
                    <th scope="col">Macedonia Verduras</th>
                    <th scope="col">Fruta en conserva Pera</th>
                    <th scope="col">Fruta en conserva Coctel</th>
                    <th scope="col">Tarito Pollo</th>
                    <th scope="col">Tarito Fruta</th>
                    <th scope="col">Leche</th>
                    <th scope="col">Batido de Chocolate</th>
                    <th scope="col">Aceite de Oliva</th>
                    <th scope="col">Modificado Por:</th>
                    <th colspan="3" scope="col">Actiones:</th>
                </tr>
            </thead>
            <tbody>
                {% for alimento in almacen_adra %}
                <tr>
                    <td>{{ alimento.arroz_blanco }}</td>
                    <td>{{ alimento.garbanzo_cocido }}</td>
                    <td>{{ alimento.atun_sardina }}</td>
                    <td>{{ alimento.sardina }}</td>
                    <td>{{ alimento.pasta_espagueti }}</td>
                    <td>{{ alimento.tomate_frito }}</td>
                    <td>{{ alimento.galletas }}</td>
                    <td>{{ alimento.macedonia_verdura_conserva }}</td>
                    <td>{{ alimento.fruta_conserva_pera }}</td>
                    <td>{{ alimento.fruta_conserva_coctel }}</td>
                    <td>{{ alimento.tarito_pollo }}</td>
                    <td>{{ alimento.tarito_fruta }}</td>
                    <td>{{ alimento.leche }}</td>
                    <td>{{ alimento.batido_chocolate }}</td>
                    <td>{{ alimento.aceite_de_oliva }}</td>
                    <td>{{ alimento.modificado_por }}</td>
                    {#                <td><a href="{% url 'adra:persona-detail' persona.id %}">Ver</a></td>#}

        {#                <td><a href="{% url 'adra:persona-update-alimentos' alimento.id %}">Editar</a></td>#}

        {#                <td><a href="{% url 'adra:persona-alimentos-delete' alimento.id %}">Sterge</a></td>#}
                </tr>
                {% empty %}
                <p>Nu sa dat alimente acestei personane :(</p>
                {% endfor %}
            </tbody>
        </table>
    </div>

        {#    <a class="btn btn-success" role="button" href="{% url 'adra:alimentos-create' persona.id %}">Repartir Alimento#}
    {#        para {{ object.nombre_apellido }}</a>#}
    {% endblock %} -->

</div>